inherit_from: rubocop-todo.yml

AllCops:
  Excludes:
    - 'config/**'
    - 'db/**'
    - 'script/**'
    - 'tmp/**'
    - 'vendor/**'
    - 'spec/fixtures/*.rb'
    - 'spec/dummy/**'
  RunRailsCops: true

# Use UTF-8 as the source file encoding.
Encoding:
  Enabled: false

# Limit lines to 80 characters.
LineLength:
  Max: 120

# Avoid methods longer than 10 lines of code
MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

BracesAroundHashParameters:
  Enabled: false

SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space

AmbiguousRegexpLiteral:
  Exclude:
    - 'spec/**'

CyclomaticComplexity:
  Max: 15 # should be set to 6, too many for now

################################################################## DISABLED COPS
# These cops are disabled because we think they are a Bad Idea. If you add one
# here, make sure to add a comment describing what the cop does, and why this
# is a bad idea.

# Forces the argument names of the block given to #reduce to be `a, e`. Only
# applies on single-line blocks, but why would we want to force people to use
# less descriptive names?
SingleLineBlockParams:
  Enabled: false

# Complains than multiline ternary expressions should be if/else statements
# Ternary are still often more readable. 
MultilineTernaryOperator:
  Enabled: false

# disallows `class Quby::Items::Text` style definitions.
# Why waste all that indentation?
ClassAndModuleChildren:
  Enabled: false

# Complains when using if-block for a single line.
# I believe an if-block is preferable when the branch is important for reading the flow
# the single line version is for when the condition is an afterthought - Henk.
IfUnlessModifier:
  Enabled: false

# before_filter must be renamed to before_action.
# can't enable this until we drop support for rails 3.
ActionFilter:
  Enabled: false
